# Site settings
title: (logistician) => { new Developer(); }
header-img: img/home-bg.png
email: bairinc@gmail.com
copyright_name: nicholasbair
description: > # this means to ignore newlines until "baseurl:"
  // Insert something funny here
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: _nickbair
github_username:  nicholasbair
learn_profile: nicholasbair
email_username: bairinc@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
